/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prakdkpta;

import java.awt.Component;
import javax.swing.JRadioButton;
import javax.swing.JOptionPane;
import static prakdkpta.Register.username;

/**
 *
 * @author asihd
 */
public class Home extends javax.swing.JFrame {
    int pajak, pajakbri, pajakbca, pajakmandiri, pajakbsi, pajakbni, nominal, total;
        

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        jLabel2.setText(Register.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rb_bri = new javax.swing.JRadioButton();
        rb_bni = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_pajak = new javax.swing.JTextField();
        txt_nominal = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rb_mandiri = new javax.swing.JRadioButton();
        rb_bca = new javax.swing.JRadioButton();
        rb_bsi = new javax.swing.JRadioButton();
        btn_input = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_clear = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        txt_jenis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(853, 542));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 41, 85));
        jLabel1.setText("WELCOME, ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 50));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 41, 85));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 190, 40));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 41, 85));
        jLabel3.setText("Mau transfer ke siapa hari ini?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setOpaque(false);

        rb_bri.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        rb_bri.setForeground(new java.awt.Color(255, 255, 255));
        rb_bri.setText("BRI");
        rb_bri.setOpaque(false);
        rb_bri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_briActionPerformed(evt);
            }
        });

        rb_bni.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        rb_bni.setForeground(new java.awt.Color(255, 255, 255));
        rb_bni.setText("BNI");
        rb_bni.setOpaque(false);
        rb_bni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_bniActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pajak");

        txt_pajak.setEditable(false);
        txt_pajak.setBackground(new java.awt.Color(0, 0, 0));
        txt_pajak.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_pajak.setForeground(new java.awt.Color(255, 255, 255));
        txt_pajak.setOpaque(false);

        txt_nominal.setBackground(new java.awt.Color(255, 255, 255));
        txt_nominal.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nominalActionPerformed(evt);
            }
        });
        txt_nominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nominalKeyReleased(evt);
            }
        });

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(0, 0, 0));
        txt_total.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 255, 255));
        txt_total.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nominal");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total");

        rb_mandiri.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        rb_mandiri.setForeground(new java.awt.Color(255, 255, 255));
        rb_mandiri.setText("Mandiri");
        rb_mandiri.setOpaque(false);
        rb_mandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mandiriActionPerformed(evt);
            }
        });

        rb_bca.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        rb_bca.setForeground(new java.awt.Color(255, 255, 255));
        rb_bca.setText("BCA");
        rb_bca.setOpaque(false);
        rb_bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_bcaActionPerformed(evt);
            }
        });

        rb_bsi.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        rb_bsi.setForeground(new java.awt.Color(255, 255, 255));
        rb_bsi.setText("BSI");
        rb_bsi.setOpaque(false);
        rb_bsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_bsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb_bca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_bri)
                            .addComponent(rb_mandiri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_bsi)
                            .addComponent(rb_bni))
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nominal)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_bri)
                    .addComponent(rb_bni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_mandiri)
                    .addComponent(rb_bsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_bca)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 230));

        btn_input.setBackground(new java.awt.Color(40, 41, 85));
        btn_input.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_input.setText("Input Data");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        txt_area.setEditable(false);
        txt_area.setBackground(new java.awt.Color(255, 255, 255));
        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        txt_area.setForeground(new java.awt.Color(0, 0, 0));
        txt_area.setRows(5);
        txt_area.setText("Nama Nasabah\t:\n\nNominal Transfer\t:\n\nPajak\t\t:\n\nTotal Transfer\t:");
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 410, 190));

        btn_clear.setBackground(new java.awt.Color(40, 41, 85));
        btn_clear.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear Data");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        btn_transaksi.setBackground(new java.awt.Color(40, 41, 85));
        btn_transaksi.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setText("Lakukan Transaksi");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        btn_keluar.setBackground(new java.awt.Color(40, 41, 85));
        btn_keluar.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        txt_jenis.setText("jTextField1");
        txt_jenis.setOpaque(false);
        jPanel1.add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\undip\\dkp\\praktikum\\TA\\how-to-create-cool-website-backgrounds-the-ultimate-guide.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -120, 1200, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_briActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_briActionPerformed
        // TODO add your handling code here:
        
        if(rb_bri.isSelected())
        {
            pajakbri=0;
            txt_pajak.setText(String.valueOf(pajakbri));
            rb_bni.setSelected(false);
        }
        JRadioButton[] buttons = new JRadioButton[]{rb_bsi, rb_bca, rb_mandiri, rb_bni};
        for (JRadioButton btn : buttons) {
            btn.setEnabled(false);
        }
    }//GEN-LAST:event_rb_briActionPerformed

    private void txt_nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nominalActionPerformed

    private void txt_nominalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nominalKeyReleased
        // TODO add your handling code here:
        nominal=Integer.parseInt(txt_nominal.getText());
        pajak=Integer.parseInt(txt_pajak.getText());
        total=nominal+pajak;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_nominalKeyReleased

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_pajak.setText("");
        txt_nominal.setText("");
        txt_total.setText("");
        txt_area.setText(
        "Nama Nasabah   :"+"\n"+
        "Nominal Transfer    :"+"\n"+
        "Pajak      :"+"\n"+
        "Total Transfer :");
        JRadioButton[] buttons = new JRadioButton[]{rb_bri, rb_bsi, rb_bca, rb_mandiri, rb_bni};
        for (JRadioButton btn : buttons) {
            btn.setEnabled(true);
        }
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        txt_area.setText(
        "Nama Nasabah            : "+username+"\n"+
        "Nominal Transfer    : "+txt_nominal.getText()+"\n"+
        "Pajak                             : "+txt_pajak.getText()+"\n"+
        "Total Transfer         : "+txt_total.getText());
    }//GEN-LAST:event_btn_inputActionPerformed

    private void rb_bniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_bniActionPerformed
        // TODO add your handling code here:
        if(rb_bni.isSelected())
        {
            pajakbni=2000;
            txt_pajak.setText(String.valueOf(pajakbni));
            
        }
            JRadioButton[] buttons = new JRadioButton[]{rb_bri, rb_bsi, rb_bca, rb_mandiri};
            for (JRadioButton btn : buttons) {
            btn.setEnabled(false);
        }
    }//GEN-LAST:event_rb_bniActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null, "Transaksi Berhasil, Lakukan Lagi?", "Berhasil", JOptionPane.OK_OPTION);
        rb_bni.setSelected(false);
        rb_bri.setSelected(false);
       
        txt_pajak.setText("");
        txt_nominal.setText("");
        txt_total.setText("");
        txt_area.setText(
        "Nama Nasabah   :"+"\n"+
        "Nominal Transfer    :"+"\n"+
        "Pajak      :"+"\n"+
        "Total Transfer :");
        
        if(answer==JOptionPane.NO_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null, "Yakin sudah selesai?", "Keluar", JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void rb_mandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mandiriActionPerformed
        // TODO add your handling code here:
        if(rb_mandiri.isSelected())
        {
            pajakmandiri=1000;
            txt_pajak.setText(String.valueOf(pajakmandiri));
        }
        JRadioButton[] buttons = new JRadioButton[]{rb_bri, rb_bsi, rb_bca, rb_bni};
        for (JRadioButton btn : buttons) {
            btn.setEnabled(false);
        }
    }//GEN-LAST:event_rb_mandiriActionPerformed

    private void rb_bsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_bsiActionPerformed
        // TODO add your handling code here:
        if(rb_bsi.isSelected())
        {
            pajakbsi=3000;
            txt_pajak.setText(String.valueOf(pajakbsi));
        }
        JRadioButton[] buttons = new JRadioButton[]{rb_bri, rb_bca, rb_mandiri, rb_bni};
        for (JRadioButton btn : buttons) {
            btn.setEnabled(false);
        }
    }//GEN-LAST:event_rb_bsiActionPerformed

    private void rb_bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_bcaActionPerformed
        // TODO add your handling code here:
        if(rb_bca.isSelected())
        {
            pajakbca=1500;
            txt_pajak.setText(String.valueOf(pajakbca));
        }
        JRadioButton[] buttons = new JRadioButton[]{rb_bri, rb_bsi, rb_mandiri, rb_bni};
        for (JRadioButton btn : buttons) {
            btn.setEnabled(false);
        }
    }//GEN-LAST:event_rb_bcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_bca;
    private javax.swing.JRadioButton rb_bni;
    private javax.swing.JRadioButton rb_bri;
    private javax.swing.JRadioButton rb_bsi;
    private javax.swing.JRadioButton rb_mandiri;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_nominal;
    private javax.swing.JTextField txt_pajak;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
